[package]
name = "raminspect"
version = "2.0.0"
edition = "2021"

license = "GPL-3.0"
readme = "cargo_readme.md"
repository = "https://github.com/ljgermain/raminspect"
description = "A library for the arbitrary inspection and manipulation of the memory and code of a process on a Linux system."

[dependencies]
procfs = "0.16"
nix = { version = "0.29", features = ["ioctl", "signal", "user", "process", "uio"] }